name: adrevauth
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1
  plugin_platform_interface: ^2.1.8
  google_mobile_ads: ^6.0.0
  http: ^1.5.0
  shared_preferences: ^2.5.3
  rxdart: ^0.28.0
  package_info_plus: ^8.0.0 # Added package_info_plus

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.adrevauth
        pluginClass: AdrevauthPlugin
      ios:
        pluginClass: AdrevauthPlugin
      linux:
        pluginClass: AdrevauthPlugin
      macos:
        pluginClass: AdrevauthPlugin
      windows:
        pluginClass: AdrevauthPluginCApi
      web:
        pluginClass: AdrevauthWeb
        fileName: adrevauth_web.dart

  assets:
    - images/

    
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          style: italic
    - family: GROBOLD
      fonts:
        - asset: fonts/GROBOLD.ttf
 